= Metanorma mn2pdf

image:https://github.com/metanorma/mn2pdf/workflows/test/badge.svg["Build Status", link="https://github.com/metanorma/mn2pdf/actions?workflow=test"]

== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]

== Java Requirements

You will need the Java Development Kit (JDK) version 8, Update 241 (8u241) or higher.


== Usage

[source,sh]
----
java -Xss5m -Xmx2048m -jar target/mn2pdf-1.89.jar --xml-file <XML-FileName> --xsl-file <XSLT-FileName> --pdf-file <Output-PDF-FileName> [--syntax-highlight]
----

e.g.

[source,sh]
----
java -Xss5m -Xmx2048m -jar target/mn2pdf-1.89.jar --xml-file tests/G.191.xml --xsl-file tests/itu.recommendation.xsl --pdf-file tests/G.191.pdf
----

=== PDF encryption features

==== via command-line options

|===
|parameter | description

|--encryption-length <integer> | encryption length in bit
|--owner-password <string> | owner password
|--user-password <string> | user password
|--allow-print <true(default)\|false> | 'false' for disable printing
|--allow-copy-content <true(default)\|false> | 'false' for disable copy/paste of content
|--allow-edit-content <true(default)\|false> | 'false' for disable editing
|--allow-edit-annotations <true(default)\|false> | 'false' for disable editing of annotations
|--allow-fill-in-forms <true(default)\|false> | 'false' for disable filling in forms
|--allow-access-content <true(default)\|false> | 'false' for disable text and graphics extraction for accessibility purposes
|--allow-assemble-document <true\|false(default)> | 'false' for disable assembling documents
|--allow-print-hq <true(default)\|false> | 'false' for disable high quality printing
|--encrypt-metadata <true(default)\|false> |'false' for disable encrypt the Metadata stream
|===

==== via YAML file (`--encryption-parameters <filename>`)
[source,yaml]
----
encryption-length: 128
owner-password: mypass
user-password: userpass
allow-print: false
allow-print-hq: true
allow-copy-content: true
allow-edit-content: false
allow-edit-annotations: true
allow-fill-in-forms: false
allow-access-content: true
allow-assemble-document: false
encrypt-metadata: true
----



== Building the package

mn2pdf depends on another packages which published in GitHub Packages registry. Regarding https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry you need an access token to install these packages.
Please set the environment variable GH_TOKEN for building the mn2pdf package.

For Windows OS:
[source,sh]
----
SET GH_TOKEN=<your GitHub token>
----

For Linux:
[source,sh]
----
GH_TOKEN=<your GitHub token>
----

To build:

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>org.metanorma.fop</groupId>
<artifactId>mn2pdf</artifactId>
<version>1.89</version>
<name>Metanorma XML to PDF converter</name>
----

Build the package using instructions above, the package will be created at:
`target/mn2pdf-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v1.89
git push origin v1.89
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/mn2pdf/releases

And downloadable at:
`https://github.com/metanorma/mn2pdf/releases/download/v{version}/mn2pdf-{version}.jar`


== Testing

The testing environment utilizes these tools:

* `make`

We use the ITU Recommendation XSLT for testing. It requires the following fonts installed:

* Times New Roman
* Arial

Please follow the instructions here to install prerequisites to run the tests:
https://github.com/metanorma/mn-native-pdf

Running the tests:

[source,sh]
----
make test
----


== Copyright

Ribose Inc.
