= Metanorma mn2pdf

image:https://github.com/metanorma/mn2pdf/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/mn2pdf/actions?workflow=ubuntu"]
image:https://github.com/metanorma/mn2pdf/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/mn2pdf/actions?workflow=macos"]
image:https://github.com/metanorma/mn2pdf/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/mn2pdf/actions?workflow=windows"]

== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]


== Usage

[source,sh]
----
java -Xss5m -Xmx1024m -jar target/mn2pdf-1.10.jar --xml-file <XML-FileName> --xsl-file <XSLT-FileName> --pdf-file <Output-PDF-FileName>
----

e.g.

[source,sh]
----
java -Xss5m -Xmx1024m -jar target/mn2pdf-1.10.jar --xml-file tests/G.191.xml --xsl-file tests/itu.recommendation.xsl --pdf-file tests/G.191.pdf
----


== Building the package

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>com.metanorma.fop</groupId>
<artifactId>mn2pdf</artifactId>
<version>1.10</version>
<name>Metanorma XML to PDF converter</name>
----

Build the package using instructions above, the package will be created at:
`target/mn2pdf-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v1.10
git push origin v1.10
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/mn2pdf/releases

And downloadable at:
`https://github.com/metanorma/mn2pdf/releases/download/v{version}/mn2pdf-{version}.jar`


== Testing

The testing environment utilizes these tools:

* `make`

We use the ITU Recommendation XSLT for testing. It requires the following fonts installed:

* Times New Roman
* Arial

Please follow the instructions here to install prerequisites to run the tests:
https://github.com/metanorma/mn-native-pdf

Running the tests:

[source,sh]
----
make test
----


== Copyright

Ribose Inc.
