name: macos

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # cabextract for fonts
      - name: Setup prerequisites
        run: |
          # Install Maven
          brew install maven

          # Install p7zip
          brew install p7zip
          # Install cabextract
          brew install cabextract

      - uses: actions/checkout@master

      - name: Install Microsoft Vista fonts
        run: |
          export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts
          export MS_FONT_PATH=${MN_PDF_FONT_PATH}/truetype/vista
          export RENAME_FONTS=false
          curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | bash

      - name: Install System Fonts
        run: |
          export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts
          mkdir -p ${MN_PDF_FONT_PATH}/truetype/msttcorefonts
          ls -alR /System/Library/Fonts
          ln -s /System/Library/Fonts/Supplemental/Arial.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arial.ttf
          ln -s /System/Library/Fonts/Supplemental/Arial\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arialbd.ttf
          ln -s /System/Library/Fonts/Supplemental/Arial\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/ariali.ttf
          ln -s /System/Library/Fonts/Supplemental/Arial\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arialbi.ttf
          ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/times.ttf
          ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesbd.ttf
          ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesi.ttf
          ln -s /System/Library/Fonts/Supplemental/Times\ New\ Roman\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/timesbi.ttf
          ln -s /System/Library/Fonts/Supplemental/Courier\ New.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/cour.ttf
          ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Bold.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/courbd.ttf
          ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Bold\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/courbi.ttf
          ln -s /System/Library/Fonts/Supplemental/Courier\ New\ Italic.ttf ${MN_PDF_FONT_PATH}/truetype/msttcorefonts/couri.ttf
          ls -alR ${MN_PDF_FONT_PATH}

      - name: Build
        run: |
          make all

      - name: Run tests
        run: |
          export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts
          ls -alR ${MN_PDF_FONT_PATH}
          make test
