name: macos

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # cabextract for fonts
      - name: Setup prerequisites
        run: |
          # Install Maven
          brew install maven

          # Install `envsubst`
          brew install gettext
          brew link --force gettext

          # Install cabextract
          brew install cabextract

      - name: Install Microsoft Vista fonts
        run: |
          export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts
          export MS_FONT_PATH=${MN_PDF_FONT_PATH}/truetype/vista
          export RENAME_FONTS=false
          curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | bash

      - name: Build
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
        run: |
          make all

      - name: Run tests
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
        run: |
          export MN_PDF_FONT_PATH=${GITHUB_WORKSPACE}/fonts
          ls -alR ${MN_PDF_FONT_PATH}
          make test
